---
label: Production
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: accent_color
  type: color
  label: Accent Color
  config:
    required: false
    color_format: RGB
- name: production_season_id
  type: number
  label: Production Season Id
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: key_art
  type: file
  config:
    maxSize: 0.5
  label: Key Art
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: true
    schema:
      format: html
    min: 100
    max: 500
  label: Description
pages:
- productions/test-production-1.md
- productions/test-production-2.json
